services:
  reposilite:
    image: dzikoysk/reposilite:latest
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xmx${MEMORY} ${JAVA_COMPOSE_OPTS}
      - REPOSILITE_OPTS=--port ${PORT} ${REPOSILITE_COMPOSE_OPTS}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true